name: 'Build Debian Packages'
description: 'Build all .deb packages (store + container apps)'

runs:
  using: 'composite'
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Install container-packaging-tools
      shell: bash
      run: |
        # Download and install container-packaging-tools from GitHub releases
        # Get the actual .deb asset URL from the latest release
        ASSET_URL=$(curl -s https://api.github.com/repos/hatlabs/container-packaging-tools/releases/latest | \
          jq -r '.assets[] | select(.name | endswith(".deb")) | .browser_download_url')

        if [ -z "$ASSET_URL" ]; then
          echo "Error: Could not find .deb asset in latest release"
          exit 1
        fi

        echo "Downloading: $ASSET_URL"
        curl -L -o container-packaging-tools.deb "$ASSET_URL"
        sudo dpkg -i container-packaging-tools.deb || sudo apt-get install -f -y
        rm container-packaging-tools.deb

    - name: Build packages
      shell: bash
      run: ./tools/build-all.sh
