name: 'Build Debian Packages'
description: 'Build all .deb packages (store + container apps)'

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install uv
      uses: astral-sh/setup-uv@v5

    - name: Install Debian packaging tools
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          debhelper \
          dh-python \
          build-essential \
          fakeroot \
          devscripts \
          dpkg-dev \
          python3-all

    - name: Build packages
      shell: bash
      run: ./tools/build-all.sh
