name: 'Build Debian Packages'
description: 'Build all .deb packages (store + container apps)'

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install uv
      uses: astral-sh/setup-uv@v5

    - name: Install Debian packaging tools
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          debhelper \
          dh-python \
          build-essential \
          fakeroot \
          devscripts \
          dpkg-dev \
          python3-all

    - name: Build packages
      shell: bash
      env:
        # Build-time placeholder for registry URL generation.
        # Uses RFC 2606 reserved domain to clearly indicate this is not a real hostname.
        # The actual URL is determined at runtime by homarr-container-adapter.
        HALOS_HOSTNAME: build.example.local
      run: ./tools/build-all.sh
