name: 'Build Debian Packages'
description: 'Build all .deb packages (store + container apps)'

runs:
  using: 'composite'
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: docker/Dockerfile.build
        tags: marine-builder
        load: true
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Build packages in Docker
      shell: bash
      run: |
        docker run --rm \
          -u $(id -u):$(id -g) \
          -v "$PWD:/workspace" \
          -w /workspace \
          marine-builder \
          ./tools/build-all.sh
