name: 'Run Tests'
description: 'Run all tests for halos-marine-containers'

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      shell: bash
      run: pip install pytest pyyaml

    - name: Run pytest tests
      shell: bash
      run: python -m pytest tests/ -v

    - name: Validate YAML syntax
      shell: bash
      run: python -c 'import yaml; yaml.safe_load(open("store/marine.yaml"))'
